### ISSUE TITLE
Struggling to install on MacOs

### ISSUE THREAD

**Issue by r-richmond** [gamax92/wine-overwatch#22]
So following @zekesonxx 's tutorial in #5 I got to step 12 before receiving 

macos 10.12.5 if relevant
ran these before following the guide
```
brew cask install xquartz
brew install --only-dependencies --devel wine
```

```
STRIPPROG="strip" ../wine-overwatch/tools/install-sh  dlls/npptools/npptools.dll.so /Applications/Wine/wine-install//usr/local/lib64/wine/npptools.dll.so
../wine-overwatch/tools/install-sh -m 644  dlls/npptools/npptools.dll.fake /Applications/Wine/wine-install//usr/local/lib64/wine/fakedlls/npptools.dll
gcc -m64 -c -o signal_x86_64.o ../../../wine-overwatch/dlls/ntdll/signal_x86_64.c -I. \
  -I../../../wine-overwatch/dlls/ntdll -I../../include -I../../../wine-overwatch/include \
  -D__WINESRC__ -D_NTSYSTEM_ -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing \
  -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits \
  -Wvla -Wwrite-strings -Wpointer-arith -gdwarf-2 -gstrict-dwarf -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:1222:45: warning: taking the absolute value of unsigned type 'ULONG_PTR' (aka 'unsigned long') has no effect [-Wabsolute-value]
        case DW_OP_abs:         stack[sp] = labs(stack[sp]); break;
                                            ^
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:1222:45: note: remove the call to 'labs' since unsigned values cannot be negative
        case DW_OP_abs:         stack[sp] = labs(stack[sp]); break;
                                            ^~~~
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:2711:10: warning: overflow converting case value to switch condition type (-1 to 65535) [-Wswitch]
    case TRAP_x86_UNKNOWN:   /* Unknown fault code */
         ^
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:2759:10: error: use of undeclared identifier 'SI_KERNEL'
    case SI_KERNEL:    /* Software breakpoint */
         ^
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:2767:33: error: use of undeclared identifier 'SI_KERNEL'
        if (siginfo->si_code == SI_KERNEL && TRAP_sig(ucontext) != TRAP_x86_BPTFLT)
                                ^
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:2768:77: warning: format specifies type 'long long' but the argument has type '__uint16_t' (aka 'unsigned short') [-Wformat]
            FIXME( "si_code == SI_KERNEL, but TRAP_sig(context) == %lld\n", TRAP_sig(ucontext) );
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
                                                                   %hu
../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:270:30: note: expanded from macro 'TRAP_sig'
#define TRAP_sig(context)    ((context)->uc_mcontext->__es.__trapno)
                             ^
../../../wine-overwatch/include/wine/debug.h:91:49: note: expanded from macro '__WINE_DBG_LOG'
    wine_dbg_log( __dbcl, __dbch, __FUNCTION__, args); } } while(0)
                                                ^~~~
3 warnings and 2 errors generated.
make[1]: *** [signal_x86_64.o] Error 1
make: *** [dlls/ntdll] Error 2
```

question for @gamax92 . Is it possible to get the official 
`brew install wine` command to install from this repo?
I looked up various commands like `brew install wine head` or `brew install wine --devel` but those appear to be hardcoded  [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wine.rb) 

note: I'm definitely in a little bit over my head here but any help is greatly appreciated
note2: previously i had commented in #5 but I felt it was probably better to break this out as it appears to be a separate issue.

**Comment by zekesonxx** [comment]
> ```
>  ../../../wine-overwatch/dlls/ntdll/signal_x86_64.c:2759:10: error: use of undeclared identifier 'SI_KERNEL'
>     case SI_KERNEL:    /* Software breakpoint */
>          ^

There's your problem right there. `SI_KERNEL` is a Linux symbol. The ntdll hooks Overwatch needs are currently only implemented if you're running on a Linux kernel, it won't work on macOS. You could make a macOS-compatible version of those hooks, but there's a slightly bigger problem:

Wine D3D11 running Overwatch needs at *least* OpenGL 4.3, preferably 4.5+. Apple refuses to update OpenGL on macOS past 4.1 because they want people using Metal or some shit. Meaning, even if you did make a macOS implementation of the anti-debugger ntdll hooks, the game wouldn't work anyways.

Unless you (or someone else) is willing to put a lot of work into the ntdll hooks and getting Wine D3D11 to work on OGL4.1, **wine-ow is probably never going to work on macOS**. Sorry.

If you have an AMD or Nvidia GPU you could use Bootcamp to run Linux, and then run wine-ow there.

**Comment by zekesonxx** [comment]
@r-richmond out of curiosity (since I don't have a Mac), can you edit `dlls/ntdll/signal_x86_64.c`, change the references from `SI_KERNEL` to `EXC_BREAKPOINT`, and then try compiling? AFAICT that's the equivalent symbol, and I'm curious how far it would get compiling with that change.

**Comment by r-richmond** [comment]
ahh ok no worries... I was under the impression it would work given the generic read me from wine...
```
3. REQUIREMENTS
To compile and run Wine, you must have one of the following:
  ...
  Mac OS X 10.5 or later 
```
guess that should be edited out. 

and sorry one last question I was under the impression wine 2.12 implements Wine D3D11 ... I was able to run `brew install wine --devel` without error ... so what am i missing?

edit* I'll give that edit a try thanks

**Comment by r-richmond** [comment]
hmm well it finished compiling but there appears to be a text rendering issue of some sort..

I was able to guess my way through the install screen but now i'm stuck regardless of wether i run the following command from wine32-build or wine64-build

<img width="834" alt="screen shot 2017-07-19 at 8 08 46 pm" src="https://user-images.githubusercontent.com/9246654/28398957-dfc8f732-6cbe-11e7-955c-68eb80c656ae.png">

<img width="1249" alt="screen shot 2017-07-19 at 8 13 24 pm" src="https://user-images.githubusercontent.com/9246654/28398972-fa82bc70-6cbe-11e7-84fa-264aa005b502.png">

I tried installing free type with `brew install freetype` however this didn't resolve the issue... but I did this after compiling... Perhaps I need to recompile everything having freetype already installed? 

(Its gotten late here so i'll try again tomorrow, thanks for your curiosity regardless)

**Comment by zekesonxx** [comment]
Wow I was *not* expecting a successful compile out of that. That doesn't really prove anything working yet, but it's cool nonetheless.

> and sorry one last question I was under the impression wine 2.12 implements Wine D3D11 ... I was able to run brew install wine --devel without error ... so what am i missing?

Just because it compiles doesn't mean it'll *work*. And Wine D3D11's OpenGL needs are based on the D3D11 application it's translating, it's very possible some D3D11 games will work with OpenGL 4.1, but according to Andrew Wesie's notes Overwatch is not one of them.

> I tried installing free type with brew install freetype however this didn't resolve the issue... but I did this after compiling... Perhaps I need to recompile everything having freetype already installed?

I believe so, yes.

**Comment by zekesonxx** [comment]
@r-richmond I just did a quick patch that should allow wine-ow to compile out of the box on macOS: https://github.com/zekesonxx/wine-overwatch/tree/macos-compile-fix. I still don't have a Mac, so if you could try that and let me know if it works.

Also, did you get anywhere recompiling with freetype installed?

**Comment by r-richmond** [comment]
well i'm actually quite confused now as after installing freetype I'm hitting new errors...  I think i need to spend some time figuring out how [brew installs wine](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wine.rb) as it appears to be installing both the 64 & 32... 

Anyways in case you're still curious here are my notes
* created super [basic install script](https://gist.github.com/r-richmond/2fb9c2c90561a13903ffd069f1f300ca)
* running the script at first results in 
```
checking for -lfreetype... not found
configure: error: FreeType 32-bit development files not found. Fonts will not be built.
Use the --without-freetype option if you really want this.
build_32 failed
```
* I attempted to install again with the --without-freetype option but then received

```
ld: warning: pointer not aligned at address 0x375FF (.L__wine_user_1001 + 3 from user.exe16-ZbdpxO.spec.o)
ld: warning: pointer not aligned at address 0x3760A (.L__wine_user_1010 + 3 from user.exe16-ZbdpxO.spec.o)
ld: warning: pointer not aligned at address 0x377EF (wine_ldt_copy_ptr + 0 from user.exe16-ZbdpxO.spec.o)
/Applications/Wine/wine64-build/tools/winegcc/winegcc -o user.exe16.fake \
  -B/Applications/Wine/wine64-build/tools/winebuild --sysroot=../.. -m32 \
  -fasynchronous-unwind-tables -shared /Applications/Wine/wine-overwatch/dlls/user.exe16/user.exe16.spec \
  -m16 -Wb,--main-module,user32.dll,--heap,65520 bidi.o comm.o dialog.o hook.o message.o network.o \
  user.o window.o version.res -lmpr -luser32 -lgdi32 ../../libs/port/libwine_port.a 
/Applications/Wine/wine-overwatch/dlls/user32/cursoricon.c:35:10: fatal error: 'png.h' file not found
#include <png.h>
         ^
gcc -m32 -c -o dde_client.o /Applications/Wine/wine-overwatch/dlls/user32/dde_client.c -I. \
  -I/Applications/Wine/wine-overwatch/dlls/user32 -I../../include \
  -I/Applications/Wine/wine-overwatch/include -D__WINESRC__ -D_USER32_ -D_WINABLE_ -D_REENTRANT \
  -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wvla -Wwrite-strings -Wpointer-arith \
  -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
1 error generated.
make[1]: *** [cursoricon.o] Error 1
.....
echo "user32_test.exe TESTRES \"user32_test-stripped.exe.so\"" | /Applications/Wine/wine64-build/tools/wrc/wrc -o ../../../programs/winetest/user32_test.res
make_32 failed
```

**Comment by zekesonxx** [comment]
It looks like Homebrew does several hacky things to get Wine to compile right.

I think you should be able to use the existing homebrew formula by changing:

```ruby
  devel do
    url "https://dl.winehq.org/wine/source/2.x/wine-2.12.tar.xz"
    mirror "https://downloads.sourceforge.net/project/wine/Source/wine-2.12.tar.xz"
    sha256 "496c11af841487e6ec4e1953ac19b05a7f48e397da502653ffbd9fe9004213a7"
```

to:

```ruby
  devel do
      head "https://github.com/zekesonxx/wine-overwatch.git", :branch => "macos-compile-fix"
```

and then try and install that.

**Comment by r-richmond** [comment]
Ok, so i spent some time mucking with this and it now installs & compiles wine correctly but I think I may be at a stopping point now.  (Although sooner than expected).

When running the battle.net launcher I get an error 'failed to initialize graphics context' although it seems strange that I would error out here... (perhaps its because of the incompatible changes you mentioned)... 

anyways gonna spend some more time googling mac Os wine installation and config.  Including just getting the battle.net launcher to run with the normal wine --devel which i think is 2.13 now.

If something sticks out to you in the screen shot let me know.

<img width="1055" alt="screen shot 2017-07-25 at 10 33 10 am" src="https://user-images.githubusercontent.com/9246654/28585726-fca0b2bc-7125-11e7-8f11-180d98cdc78d.png">


also i edited the wine.rb to wineoverwatch.rb & as follows

```
class Wineoverwatch < Formula
  desc "Run Windows applications without a copy of Microsoft Windows"
  homepage "https://www.winehq.org/"
  head "https://source.winehq.org/git/wine.git"
  revision 1

  # stable do
  #   url "https://dl.winehq.org/wine/source/2.0/wine-2.0.2.tar.xz"
  #   mirror "https://downloads.sourceforge.net/project/wine/Source/wine-2.0.2.tar.xz"
  #   sha256 "f71884f539928877f4b415309f582825d3d3c9976104e43d566944c710713c9a"
  #
  #   # Patch to fix texture compression issues. Still relevant on 2.0.
  #   # https://bugs.winehq.org/show_bug.cgi?id=14939
  #   patch do
  #     url "https://bugs.winehq.org/attachment.cgi?id=52384"
  #     sha256 "30766403f5064a115f61de8cacba1defddffe2dd898b59557956400470adc699"
  #   end
  #
  #   # Patch to fix screen-flickering issues. Still relevant on 2.0.
  #   # https://bugs.winehq.org/show_bug.cgi?id=34166
  #   patch do
  #     url "https://bugs.winehq.org/attachment.cgi?id=55968"
  #     sha256 "1b5086798ce6dc959b3cbb8f343ee236ae06c7910e4bbae7d9fde3f162f03a79"
  #   end
  # end
  #
  # bottle do
  #   sha256 "c4df3ea1445d6c16ca1c3ab20192fffa37f0fe3952b0d9d70796a97e602e7a39" => :sierra
  #   sha256 "b8d96829e413bb9899c3522fc1bbb398334c1c4c4705db438b475bc619dc12ec" => :el_capitan
  #   sha256 "7a5826a9a434f12393fe04534025ce35b50739adc9d7d6cadca775336aadd87e" => :yosemite
  # end

  devel do
    url "https://github.com/zekesonxx/wine-overwatch.git", :branch => "macos-compile-fix"

    # Patch to fix screen-flickering issues. Still relevant on 2.3.
    # https://bugs.winehq.org/show_bug.cgi?id=34166
    patch do
      url "https://bugs.winehq.org/attachment.cgi?id=57353"
      sha256 "55436526e786c3cac35c7b522f01ca5cc5b826bd0d2bd9e98f53e6a5043a151e"
    end
  end
```

**Comment by zekesonxx** [comment]
@r-richmond are you using the instructions on [the appdb page](https://appdb.winehq.org/objectManager.php?iId=28855&sClass=version) for getting bnet to behave? They're written from a Linux perspective but they should still apply on macOS.
