### ISSUE TITLE
'png.h' file not found

### ISSUE THREAD

**Issue by MegaJiXiang** [gamax92/wine-overwatch#28]
I tried to build on Mac OSX Sierra 10.12.6 and when I ran .configure it complained about freetype fonts and recommended I try ./configure --without-freetype. So that's what I did. It configured fine then I ran make.

Make failed with this message:
gcc -m32 -c -o cursoricon.o cursoricon.c -I. -I../../include -D__WINESRC__ -D_USER32_ -D_WINABLE_ -D_REENTRANT \
  -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wvla -Wwrite-strings -Wpointer-arith \
  -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
cursoricon.c:35:10: fatal error: 'png.h' file not found
#include <png.h>

Anyone know what to do?

**Comment by MegaJiXiang** [comment]
I got it to get passed that problem by pasting the .h files from libpng version 1.6.32 into the include folder in the base directory of the repo.

**Comment by MegaJiXiang** [comment]
That fix was bogus. After Googling a bit I found a real solution that worked.

brew uninstall freetype

Seems this works because I already have freetype with x11 or something but having this brew version of freetype confuses the configure process.

It totally builds without that without freetype error now.

**Comment by MegaJiXiang** [comment]
In the end I still have problems. I give up. At this point it would be cheaper to buy Windows 10 and install it with Bootcamp.

**Comment by setzer22** [comment]
Please stick to relevant information in your issue reports. Some of us are subscribed to this repo and are getting emails from each of your comments, and that last comment was totally not constructive.

**Comment by Paktosan** [comment]
You still could not play Overwatch even if you did managed to build wine properly. Because as far as I know macOS does not support the OpenGL functions required to run Overwatch. Therefore the game wouldn't run anyway.
